# Site settings
title: start.ffbsee
description:      "Frei von Registrierung, Erfassung von persönlichen Informationen oder zeitlicher Limitierung. Freifunk Bodensee ist ein Netz, an dem jeder teilnehmen kann."
baseurl: ""
organisation:     Freifunk Bodensee
twitter_username: FFBodensee
github_username:  ffbsee/start-ffbsee
about_page:       https://ffbsee.de/

# Build settings
markdown: kramdown
permalink: pretty
