# .ffbsee
# network: intern
# .com:
# network: public
#
# Pick your icon from here:
# https://fortawesome.github.io/Font-Awesome/icons/
# the fa- is added automatically
#
- title:     Seafile
  text:      Seafile ist ein Ersatz für Dropbox, gehostet im Richtfunk-Netz
  icon:      cloud-download
  url:       https://cloud.ffbsee.de
  network:   public
#- title:     schnackr
#  text:      schnackr ist ein freier, offener Twitter-Ersatz basierend auf GNUSocial.
#  icon:      comments-o
#  url:       https://schnackr.hamburg.freifunk.net
#  network:   public
- title:    Wiki
  text:     Freifunk hinter der Bühne. Unsere Wissenssammlung
  icon:     group
  url:      https://ffbsee.de
  network:  public
- title:    Verbindung
  text:     Zeigt Informationen über den Router, mit dem du gerade verbunden bist
  icon:     wifi
  url:      http://nextnode.ffbsee/
  network:  intern
- title:    Github Repo
  text:     Hier sammeln wir unseren Programmiercode für fast alles und außerdem Grafiken, Flugblätter und vieles mehr. Schaut euch um
  icon:     folder-open
  url:      http://github.com/ffbsee
  network:  public
