# .ffhh:
# network: intern
# .com:
# network: public
#
# Pick your icon from here:
# https://fortawesome.github.io/Font-Awesome/icons/
# the fa- is added automatically
#
- title:     Seafile
  text:      Seafile ist ein Ersatz f체r Dropbox, gehostet im Richtfunk-Netz
  icon:      cloud-download
  url:       https://cloud.hamburg.freifunk.net
  network:   public
#- title:    Blogs
#  text:     Worpress im Freifunk-Netz
#  icon:     quote-right
#  url:      http://wp.ffhh/
#  network:  intern
#- title:    Radio
#  text:     Live Stream von freier Musik
#  icon:     file-audio-o
#  url:      http://radio.ffhh/
#  network:  intern
- title:    Wiki
  text:     Freifunk hinter der B체hne. Unsere Wissenssammlung
  icon:     group
  url:      https://wiki.freifunk.net/Freifunk_Hamburg
  network:  public
- title:    Verbindung
  text:     Zeigt Informationen 체ber den Router, mit dem du gerade verbunden bist
  icon:     wifi
  url:      http://knoten.ffhh/
  network:  intern
#- title:    Pastebin
#  text:     Texte schnell und unkompliziert teilen
#  icon:     file
#  url:      http://paste.ffhh
#  network:  intern
- title:    ifconfig
  text:     Zeigt deine IPv4 und IPv6 Adresse
  icon:     gears
  url:      http://ifconfig.ffhh
  network:  intern
- title:    Medien
  text:     Hier sammeln wir Grafiken, Flugbl채tter und vieles mehr. Schaut euch um
  icon:     folder-open
  url:      http://media.services.ffhh/
  network:  intern
